import { Button, VerticalBox, LineEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 240px;
    min-height: 290px;
    title: "BEST ACLCULATOIR!!11!one";
    default-font-size: 12pt;

    in-out property<string> result;
    in property<string> error;
    in-out property<string> line-edit-text;

    callback input-entered(string);
    callback input-edited(string);
    callback button-pressed(string);
    callback backspace(string);

    VerticalBox {
        padding-top: 15px;
        input:= LineEdit {
            text: root.line-edit-text;
            height: 17%;
            font-size: 17pt;
            horizontal-alignment: right;
            accepted() => {
                root.input-entered(self.text);
                self.text = root.result;
                root.line-edit-text = self.text;
                self.placeholder-text = root.error;
            }
            edited => {
                // input-edited(self.text);
                root.line-edit-text = self.text;
                // self.text = line-edit-text;
            }
        }
        GridLayout {
            spacing: 3px;
            Row {
                Button {
                    text: "7";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "8";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "9";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "/";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
            }
            Row {
                Button {
                    text: "4";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "5";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "6";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "*";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
            }
            Row {
                Button {
                    text: "1";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "2";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "3";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "-";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
            }
            Row {
                Button {
                    text: ".";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "0";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: "=";
                    clicked => {
                        root.input-entered(input.text);
                        input.text = root.result;
                        root.line-edit-text = root.result;
                        input.placeholder-text = root.error;
                    }
                }
                Button {
                    text: "+";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
            }
            Row {
                Button {
                    text: "C";
                    clicked => {
                        backspace(input.text);
                        input.text = root.result;
                        line-edit-text = root.result;
                    }
                }
                Button {
                    text: "CE";
                    clicked => {
                        input.text = "";
                        root.result = "";
                        line-edit-text = "";
                    }
                }
                Button {
                    text: "(";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
                Button {
                    text: ")";
                    clicked => {
                        input.clear-focus();
                        button-pressed(self.text);
                        input.text = root.line-edit-text;
                        input-edited(input.text);
                        input.text = root.line-edit-text;
                    }
                }
            }
        }
    }
}
