import { Button, VerticalBox, LineEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 300px;
    height: 150px;
    padding: 20px;
    title: "BEST ACLCULATOIR!!11!one";
    default-font-size: 15pt;

    in property<string> result;
    in property<string> errors;
    in-out property<string> line-edit-text;

    callback input-entered(string);
    callback button-pressed(string);

    VerticalBox {
        input:= LineEdit {
            text: root.line-edit-text;
            horizontal-alignment: right;
            accepted() => {
                root.input-entered(self.text);
            }
        }
        Text {
            text: root.result;
        }
        HorizontalBox {
            Button {
                text: "0";
                clicked => {
                    input.clear-focus();
                    button-pressed(self.text);
                }
            }
        }
    }
}
